common/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from common.views import CategoryDetailView, ProductDetailView
from core.settings import CACHES

time_cache = CACHES['default']['TIMEOUT']

urlpatterns = [
    path('category/<int:pk>', cache_page(time_cache, key_prefix='category_pk')(CategoryDetailView.as_view()), name='category'),
    path('product/<int:pk>', cache_page(time_cache, key_prefix='product')(ProductDetailView.as_view()), name='product'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_page

from common.views import CategoryView
from core.settings import CACHES

time_cache = CACHES['default']['TIMEOUT']

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', cache_page(time_cache, key_prefix="category_list")(CategoryView.as_view()), name='category_list'),
    path('common/', include('common.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

common/models.py
import requests
from django.core.cache import cache
from django.db import models
from django.urls import reverse

from core.constants import STATUS_PRODUCT


class Category(models.Model):
    """Model for category"""

    name = models.CharField(
        verbose_name='Категория', max_length=255, unique=True
    )

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'pk': self.id})


class Product(models.Model):
    """Model for product"""

    name = models.CharField(
        verbose_name='Название товара', unique=True, max_length=255
    )
    category = models.ForeignKey(
        Category, verbose_name='Категория', on_delete=models.CASCADE,
        related_name='products'
    )
    price = models.DecimalField(
        verbose_name='Цена', max_digits=10, decimal_places=2
    )
    status = models.CharField(
        verbose_name="Статус", choices=STATUS_PRODUCT, max_length=255,
        default='Out of stock'
    )
    remains = models.IntegerField(verbose_name='Остатки', default=0)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product', kwargs={'pk': self.id})

common/views.py
from django.views.generic import ListView, DetailView

from common.models import Product, Category


class CategoryView(ListView):
    """View for category"""

    template_name = 'category-list.html'
    context_object_name = 'category_list'
    queryset = Category.objects.all()
    paginate_by = 50


class CategoryDetailView(ListView):
    """View for category detail"""

    context_object_name = 'product_list'
    template_name = 'category.html'
    paginate_by = 50

    def get_queryset(self):
        queryset = Product.objects.filter(category_id=self.kwargs.get('pk'))

        return queryset

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        context['category'] = Category.objects.get(id=self.kwargs.get('pk'))

        return context


class ProductDetailView(DetailView):
    """View for product detail"""

    model = Product
    context_object_name = 'product'
    template_name = 'product.html'

    def get_queryset(self):
        queryset = Product.objects.filter(
            id=self.kwargs.get('pk')
        ).select_related('category')

        return queryset

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

{% block content %}

{% endblock %}

{% block js %}{% endblock %}

</body>
</html>

templates/category-list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Список категорий {% endblock %}


{% block content %}
    <main>
        <div class="container">
            <h1 class="title">Список категорий</h1>
            <div class="category-list">
                {% for category in category_list %}
                    <div class="category">
                        <h3>{{ category }}</h3>
                        <a class="link" href="{{ category.get_absolute_url }}">Открыть</a>
                    </div>
                {% endfor %}
            </div>
            {% include 'paginate.html' %}
        </div>
    </main>
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ product_list.category }} {% endblock %}


{% block content %}
    <main>
        <div class="container">
            <h1 class="title">{{ category.name }}</h1>
            <a href="{% url 'category_list' %}" class="back">< Назад</a>
            <div class="category-list">
                {% for product in product_list %}
                    <div class="category">
                        <h3>{{ product.name }}</h3>
                        <div class="price"><span>Цена:</span> {{ product.price }}</div>
                        <div class="status {% if product.status == 'Out of stock' %}red{% endif %}"><span>Статус:</span> {{ product.get_status_display }}</div>
                        <div class="remains"><span>Остатки:</span> {{ product.remains }}</div>
                        <a class="link" href="{{ product.get_absolute_url }}">Открыть</a>
                    </div>
                {% endfor %}
            </div>
            {% include 'paginate.html' %}
        </div>
    </main>
{% endblock %}

templates/paginate.html
<ul class="pagination">
     <li class="page-item">
        {% if page_obj.has_previous %}
            <a class="page-link button-page" href="?page={{ page_obj.previous_page_number }}"><<</a>
        {% else %}
            <a class="page-link button-page"><<</a>
        {% endif %}
        </li>
    <li class="page-item">
        <a class="page-link number">{{ page_obj.number }}</a>
    </li>
    <li class="page-item">
        {% if page_obj.has_next %}
            <a class="page-link button-page" href="?page={{ page_obj.next_page_number }}">>></a>
        {% else %}
            <a class="page-link button-page">>></a>
        {% endif %}
    </li>
</ul>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ product.name }} {% endblock %}


{% block content %}
    <main>
        <div class="container">
            <h1 class="title">{{ product.name }}</h1>
            <a href="{% url 'category' product.category.id %}" class="back">< Назад</a>
            <div class="product-detail">
                <div class="category">
                    <div class="price"><span>Цена:</span> {{ product.price }}</div>
                    <div class="status {% if product.status == 'Out of stock' %}red{% endif %}"><span>Статус:</span> {{ product.status }}</div>
                    <div class="remains"><span>Остатки:</span> {{ product.remains }}</div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}